# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dev blog
email: unidcube@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  안녕하세요 개발자 백 의 블로그 입니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 100nw
github_username:  unidcube

# Build settings
#markdown: kramdown
#highlighter: rouge
encoding: utf-8
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "tables"]

highlighter: rouge
permalink: pretty

safe: true
lsi: true

gems:
  - jekyll-redirect-from
  - jemoji